spring.application.name=crm-backend

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/orque_crm
spring.datasource.username=krishnaprasad
spring.datasource.password=Ayuktha@63

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=IpJSwc0WpiPK1Rs6IrHGpkDCgUvzn93w5t0Zz32QgVDSTVZDRB4KPE/CcIaw/ep4
app.jwt.access-expiration=86400000
app.jwt.refresh-expiration=604800000

# Google OAuth / Gmail
google.oauth.client-id=${GOOGLE_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth.redirect-uri=${GOOGLE_REDIRECT_URI}
google.oauth.scope=https://www.googleapis.com/auth/gmail.readonly

# Jackson Configuration
spring.jackson.deserialization.fail-on-unknown-properties=false