package com.orque.crm.enums;

public enum DashboardWidgetType {
    TOTAL_CONTACTS,
    TOTAL_LEADS,
    HOT_LEADS,
    TASKS_DUE_TODAY,
    REVENUE_GENERATED,
    PIPELINE_VALUE,
    EMAIL_CAMPAIGN_STATISTICS,
    LEAD_SOURCE_DISTRIBUTION,
    CONVERSION_FUNNEL,
    MONTHLY_SALES_TREND,
    RECENT_ACTIVITIES
}